#-----------------------------------
# start up a pair of containers
# with a shared public_html
#
# the commented out line for weewx.conf
# shows how to mount a local config file
# rather than using the built-in one
#
# this uses a built image for weewx
# (see the Dockerfile for how to build)
#-----------------------------------
 weewx:
    image: weealpine:latest
    container_name: weealpine
    restart: unless-stopped
    volumes:
      - /mnt/weewx-alpine/html:/home/weewx/public_html
      - /mnt/weewx-alpine/archive:/home/weewx/archive
      - /mnt/weewx-alpine/ssh:/root/.ssh
      - /mnt/weewx-alpine/logs:/var/log
        ###- ${PWD}/weewx-alpine/configs/weewx.conf:/home/weewx/weewx.conf
nginx:
    image: nginx:1.18.0-alpine
    container_name: nginxalpine
    restart: unless-stopped
    ports:
      - "8444:80"
    volumes:
      - /mnt/weewx-alpine/html:/usr/share/nginx/html/weewx
